logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    org.springframework.boot.actuate: off
    org.springframework.web: debug
    org.springframework.boot: info
    io.swagger.models.parameters.AbstractSerializableParameter: error


spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 6100
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,text/html,text/plain,text/css,text/javascript,application/javascript,image/jpeg,image/png

app:
  uploader: local
  local-storage:
    path:
      edited-path: /var/tmp/image/edit
      un-retouched-path: /var/tmp/image/original
    url: http://localhost
    shard-type: date
  aws-s3:
    bucket: sea-otter
    path:
      edited-path: /var/tmp/image/edit
      un-retouched-path: /var/tmp/image/original
    cloud-front:
      enabled: false
      url: http://localhost
